---
logging:
  level:
    org:
      springframework:
        web: DEBUG
mysqldb:
  datasource:
    url               : jdbc:mysql://rm-bp1v548c6d7rt32o1o.mysql.rds.aliyuncs.com:3306/class_qe?characterEncoding=utf-8
    username          : root
    password          : '!@#zxcVBNM'
name: 张三